_target_: src.envs.awake.DoFWrapper
env: 
  _target_: src.envs.awake.AwakeSteering
  task:
    # Load a predefined task for verification
    _target_: src.envs.helpers.load_predefined_task
    task_nr: 0
    task_location: ./environment/tasks/verification_tasks.pkl

  MAX_TIME: 1000

DoF: 6

# Whether to enforce boundary conditions on beam positions.
boundary_conditions: true

# Initial Scaling: Scaling factor applied to initial observations to normalize state values.
init_scaling: 0.9

# Action Scale: Scaling factor applied to actions to control the magnitude of control inputs.
action_scale: 1.0

# Scaling factor applied to penalties when boundary conditions are violated.
penalty-scaling: 100.0

# Note: Modify these settings only if necessary.
noise_setting:
  # Standard deviation of noise added to observations. Set to 'none' to disable noise.
  std_noise: 0.5
