_target_: stable_baselines3.PPO
policy: MlpPolicy
env:
  _target_: stable_baselines3.common.vec_env.VecNormalize
  venv:
    _target_: stable_baselines3.common.env_util.make_vec_env
    env_id:
      _target_: gymnasium.make
      _partial_: true
      id: ${env.id}-${env.version}
    n_envs: 1
    seed: ${seed}
    wrapper_class: ${env.wrapper_class}
    wrapper_kwargs: ${env.wrapper_kwargs}
  gamma: ${agent.gamma}
  norm_reward: true
  training: true
  
learning_rate: 3.0e-4
n_steps: 2048
batch_size: 64
n_epochs: 10
gamma: 0.99
gae_lambda: 0.95
clip_range: 0.2
ent_coef: 0.0
vf_coef: 0.5
max_grad_norm: 0.5
use_sde: False
sde_sample_freq: -1
verbose: 1
tensorboard_log: ${log_dir}/tensorboard
seed: ${seed}